### ISSUE TITLE
pr2_table_object.launch file contains duplicate args for gui

### ISSUE THREAD

**Issue by cirvladimir** [PR2/pr2_simulator#105]
In the following launch file:
 pr2_simulator / pr2_gazebo / launch / pr2_table_object.launch 

lines 3 and 8 are the same so the launch fails.

**Comment by UltronDestroyer** [comment]
Ah yes, that is why this launch file was failing. 

Thank you vovakkk :)

**Comment by UltronDestroyer** [comment]
Do you mind running a pull request for this fix?

**Comment by YuOhara** [comment]
This has been fixed in https://github.com/PR2/pr2_simulator/commit/937bb1626127dc0a3aa45d7855fc0edb62fed4a2, so could you release this as deb version?

**Comment by UltronDestroyer** [comment]
Debs should have built. Closing
