### ISSUE TITLE
unused args [paused,gui] problem

### ISSUE THREAD

**Issue by janga1997** [PR2/pr2_simulator#121]
While running 
`roslaunch pr2_gazebo pr2_wg_world.launch`
it gives the error
`unused args [paused, gui] for include of [/opt/ros/jade/share/gazebo_ros/launch/willowgarage_world.launch]
The traceback for the exception was written to the log file
`
Could someone fix the error please? I am running jade on Ubuntu 14.04 LTS version.

**Comment by robograffitti** [comment]
Just comment out these 4 lines from the launch file.
https://github.com/PR2/pr2_simulator/blob/indigo-devel/pr2_gazebo/launch/pr2_wg_world.launch#L4-L5
https://github.com/PR2/pr2_simulator/blob/indigo-devel/pr2_gazebo/launch/pr2_wg_world.launch#L11-L12
