### ISSUE TITLE
Release for ROS kinetic?

### ISSUE THREAD

**Issue by jacknlliu** [PR2/pr2_simulator#127]
Is this repo ready for ros kinetic version?

**Comment by codexsameen** [comment]
I'm also working with ROS Kinetic and wish to know if this is compatible.

**Comment by rdelgadov** [comment]
@samisnotinsane you try the package? i'm thinking do a fork to start the port to kinetic but i need to know if somebody already do or not.

**Comment by codexsameen** [comment]
@rdelgadov it was too much work to set up for my requirements. I'm setting up my own simple robot by writing URDF from scratch so that I don't have extra bloat. Make a post here if you're able to run it on Kinetic. Good luck!

**Comment by k-okada** [comment]
as of 2018/3/15 it is already released.
