### ISSUE TITLE
Missing SetModelsJointsStates.h

### ISSUE THREAD

**Issue by ghost** [PR2/pr2_simulator#96]
Hi, 
I was trying to compile the pr2_gazebo_plugins package of the hydro-devel branch, but got this error. Is the file replaced by something else? Thanks a lot!

pr2_simulator/pr2_gazebo_plugins/include/pr2_gazebo_plugins/gazebo_ros_controller_manager.h:42:54: fatal error: pr2_gazebo_plugins/SetModelsJointsStates.h: No such file or directory.

**Comment by trainman419** [comment]
At first glance, this looks like a dependency issue; whichever target is including that file should depend on the msgs target.

In the meantime, you should be able to get this to build by running catkin_make a few times until it succeeds

**Comment by ghost** [comment]
Thanks for the reply. Which msgs target? 
gazebo_ros_controller_manager.h is including SetModelsJointsStates.h, which does not seem to exist anywhere.

**Comment by trainman419** [comment]
We probably need to add `${PROJECT_NAME}_generate_messages_cpp` to both of the add_dependencies calls, as per the catkin/CMake documentation: http://wiki.ros.org/catkin/CMakeLists.txt#Important_Prerequisites.2BAC8-Constraints

**Comment by ahendrix** [comment]
Fixed in 636ce3f ; compiles on my machine.
