### ISSUE TITLE
PR2 Grippers not visible in simulation.

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_simulator#97]
It looks like the frames for the PR2 grippers are not being published in simulation; in particular I'm seeing TF frame errors for both grippers and both fingers on the _finger_link, _finger_tip_frame, _finger_tip_link, _motor_screw_link and _motor_slider_link frames.

I've just merged https://github.com/PR2/pr2_mechanism/commit/c3d77a0fe80cabeb6faecc23c9bde4b0e6ad6fc0, so that may or may not be responsible.

**Comment by ahendrix** [comment]
@hsu can you take a look at this if you have a chance?

**Comment by ZdenekM** [comment]
Same problem here.

**Comment by trainman419** [comment]
I don't currently have time to work on this.

@ZdenekM if you can track this down and provide a pull requests that fixes it, I'll happily merge it.

**Comment by hsu** [comment]
Sorry, probably not going to get around to patching this week.  It may very well be that the recently merged changes (PR2/pr2_mechanism@c3d77a0) disabled joint states from being published by mistake.

**Comment by ahendrix** [comment]
Fixed in https://github.com/PR2/pr2_mechanism/commit/1156d4ec63130a2277bf842ccb124ad7d256e4c7
