### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by beranv** [PR2/pr2_simulator#98]
Ubuntu 12.10, ROS Hydro, pr2_simulator branch: hydro-devel
`/home/beranv/ros_hydro/catkin_ws/src/pr2_simulator/pr2_gazebo_plugins/src/gazebo_ros_controller_manager.cpp:47:24: fatal error: sdf/Param.hh: No such file or directory
compilation terminated.`

**Comment by trainman419** [comment]
This looks like a missing or moved header in Gazebo; which version of gazebo are you building against?

**Comment by beranv** [comment]
Thanks for great hint. Problem was two gazebos of different version (1.9.0 devel and 1.9.5). I had no info about 1.9.0 in advance and it took some effort to find it and remove. Finally, it works. Thanks,
